name: Build packages
on:
  push:
    branches:
      - master
env:
  IMAGE_NAME: archlinux-packages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: |
          docker build . --file Dockerfile -t archlinux-packages:latest
      - name: Build packages
        run: |
          docker run -e GCLOUD_CREDENTIALS archlinux-packages:latest /home/builder/script/build-packages.sh
        env:
          GCLOUD_CREDENTIALS: ${{ secrets.GCLOUD_CREDENTIALS }}
