name: Build packages
on:
  push:
    branches:
      - master
  schedule:
    - cron: "30 */2 * * *"

env:
  IMAGE_NAME: archlinux-packages
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GCLOUD_CREDENTIALS: ${{ secrets.GCLOUD_CREDENTIALS }}
    steps:
      - uses: actions/checkout@v1
      - name: Build packages
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          docker run -e GCLOUD_CREDENTIALS -v /github/workspace:/home/builder docker.pkg.github.com/ahayworth/archlinux-packages/archlinux-packages:latest /home/builder/script/build-packages.sh
