name: Build packages
on:
  push:
    branches:
      - master
  schedule:
    - cron: "30 */2 * * *"

env:
  IMAGE_NAME: archlinux-packages
jobs:
  get-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GPR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Pull image
        run: |
          docker pull docker.pkg.github.com/ahayworth/archlinux-packages/archlinux-packages:latest
  build:
    needs: get-image
    runs-on: ubuntu-latest
    env:
      GCLOUD_CREDENTIALS: ${{ secrets.GCLOUD_CREDENTIALS }}
    steps:
      - uses: actions/checkout@v1
      - name: Build packages
        run: |
          sudo cp -R /github/workspace /home/builder/
          /home/builder/script/build-packages.sh
    container:
      image: archlinux-packages:latest
      options: "-e GCLOUD_CREDENTIALS"
