name: Build packages
on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/2 * * * *"

env:
  IMAGE_NAME: archlinux-packages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build packages
        run: |
          docker pull docker.pkg.github.com/ahayworth/archlinux-packages/archlinux-packages:latest
          docker run archlinux-packages:latest /home/builder/script/build-packages.sh
        env:
          GCLOUD_CREDENTIALS: ${{ secrets.GCLOUD_CREDENTIALS }}
